### ISSUE TITLE
MerlinLocate not resolving definition of core modules

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#894]
If I have an OCaml file as follows:
```
open Core
module L = List
...
```
and I try to `MerlinLocate` on `List`, I get the following error:
```
Several source files in your path have the same name, and merlin doesn't know which is the right one:
/usr/local/lib/ocaml/list.ml, /usr/local/lib/ocaml/list.mli, /Users/dani/.opam/system/lib/core_kernel/
list.ml, /Users/dani/.opam/system/lib/core_kernel/list.mli, /Users/dani/.opam/system/lib/base/list.ml,
 /Users/dani/.opam/system/lib/base/list.mli
```
Why is Merlin having trouble selecting the right one? I'm using Merlin version 3.2.2.

(Following up on issue 2 in https://github.com/ocaml/merlin/issues/863. The behavior I had been seeing was that this issue occurred when trying to go to definition a second time, as though the locate was cached and there was an issue with the cached version, but now the issue happens even on the first locate request)

**Comment by b0o** [comment]
@ddickstein I know this issue is really old, but did you ever figure out a solution? I am experiencing the same problem.

**Comment by ddickstein** [comment]
My understanding is that [duniverse](https://github.com/avsm/duniverse), when it arrives, will solve this problem.

**Comment by ddickstein** [comment]
My understanding is that duniverse <https://github.com/avsm/duniverse>,
when it arrives, will solve this problem.

**Comment by trefis** [comment]
I don't think "the duniverse" will help at all with this.
You have several "list.ml" in your path right now, that'll still be the case with the duniverse.

That being said, I just tried to reproduce the issue right now and wasn't able to. (Though I used `Base` and not `Core`).
There have been a lot of fixes on locate since this issue was created. And perhaps this one is fixed and @b0o is actually encountering a different problem?

**Comment by trefis** [comment]
@ddickstein: can you confirm whether you can reproduce the issue or not?

**Comment by ddickstein** [comment]
Yes, this problem is still occurring for me (using merlin 3.3.2).

I'm using dune 1.9 (set in my dune-project file), an empty dune workspace file, and my dune file itself where I'm testing the jump to definition looks like this:

```
(library
  (name rocket_game)
  (inline_tests)
  (libraries core sexplib)
  (preprocess (pps ppx_jane)))
```

I guess I was mistaken about what duniverse would fix - I was told it would fix the problem of jumping to definitions from inside opam libraries, and I assumed the difficulties merlin was having with locating the right file for the initial jump was related to the library living outside my project.

**Comment by ddickstein** [comment]
Can the "Awaiting feedback" tag here be removed?

**Comment by DouglasGray** [comment]
Just a heads up I am also seeing this. If I try to jump to:
`Core.Command.Arg_type.create`

I get an error saying:
`"Several source files in your path have the same name, and merlin doesn't know which is the right one: /home/.../.opam/ocaml-base-compiler.4.09.0/lib/core_kernel/command.ml, /home/.../.opam/ocaml-base-compiler.4.09.0/lib/core/command.ml`

My version of Merlin is 3.3.3. I am using Dune (version 2.4.0) to manage my project and `.merlin` file though, so not sure if it's more appropriate to chat to the Dune folk.

**Comment by ddickstein** [comment]
I created a minimal repro case as a dune issue (I'm honestly not sure which project should host this issue, since I'm trying to solve this merlin locate problem with vendoring in dune).

https://github.com/ocaml/dune/issues/3971

**Comment by rgrinberg** [comment]
@DouglasGray I'm unable to reproduce your particular issue with the latest dune & merlin.

**Comment by voodoos** [comment]
Should be solved on master.
